name: myapp
description: "Panel Administrativo para Farmacias Similares"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Usamos estas versiones exactas para solucionar el error 'handleThenable'
  firebase_core: 2.27.0
  firebase_auth: 4.17.8
  cloud_firestore: 4.15.8
  
  # Estilo y diseño
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Si vas a usar imágenes locales, asegúrate de descomentar esto:
  # assets:
  #   - assets/logo_similares.png